name: PHP Compatibility
on: [push]
jobs:
  phpcompat:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: [ '8.0', '8.1', '8.2' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check PHP Compatibility
        uses: pantheon-systems/phpcompatibility-action@dev
        with:
          test-versions: '${{ matrix.php_version }}-'
          paths: '${{ github.workspace }}/**/*.php'